name: Report Plugin Build

on:
    workflow_run:
        workflows: ["Plugin Build"]
        types: 
          - completed

jobs:
    report-build:
        name: Report Plugin Build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Get the artifact data for current run
              id: artifacts
              uses: fjorgemota/github-action-report-artifact@main
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  artifact-name: sensei-lms-${{ github.event.workflow_run.head_sha }}
                  report-on: commit_status
                  context: Plugin Download
                  message: Click on "Details" to download the plugin build for this commit
                  